language: android
jdk: oraclejdk8
script: ./gradlew backend:build
env:
  - BUILD_MACHINE=travis
android:
  components:
    - platform-tools
    - tools
    - build-tools-25.0.0
    - android-25
    - extra-android-m2repository
    - extra-google-m2repository